# Generated by Django 5.2 on 2025-04-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0003_alter_leads_options_alter_leads_services_want_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='shop_type',
            field=models.CharField(blank=True, choices=[('supermarket', 'Supermarket'), ('saloon', 'Saloon'), ('restaurant', 'Restaurant'), ('clothing', 'Clothing Store'), ('electronics', 'Electronics Store')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('closed', 'Closed')], max_length=10, null=True),
        ),
    ]
