# Generated by Django 5.2 on 2025-04-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0004_leads_follow_up_date_alter_leads_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='service_products',
            field=models.JSONField(blank=True, help_text='Dictionary mapping services to selected products', null=True),
        ),
    ]
