# Generated by Django 5.2 on 2025-04-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0007_remove_leads_products_interested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='leads',
            name='service_products',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='services_want',
        ),
        migrations.AddField(
            model_name='leads',
            name='products_interested',
            field=models.ManyToManyField(blank=True, to='leads_app.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='leads_app.service'),
        ),
        migrations.AddField(
            model_name='leads',
            name='services_want',
            field=models.ManyToManyField(blank=True, to='leads_app.service'),
        ),
    ]
