# Generated by Django 5.2 on 2025-04-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0009_companysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='products_interested',
            field=models.ManyToManyField(blank=True, null=True, to='leads_app.product'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='services_want',
            field=models.ManyToManyField(blank=True, null=True, to='leads_app.service'),
        ),
    ]
