# Generated by Django 5.2 on 2025-04-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0010_alter_leads_products_interested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='products_interested',
            field=models.ManyToManyField(blank=True, to='leads_app.product'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='services_want',
            field=models.ManyToManyField(blank=True, to='leads_app.service'),
        ),
    ]
