# Generated by Django 5.2 on 2025-05-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0012_companyprofile_employee_delete_companysettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='lead_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/lead_images/'),
        ),
    ]
