# Generated by Django 5.2 on 2025-05-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0013_leads_lead_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_image',
            field=models.ImageField(blank=True, null=True, upload_to='lead_images/'),
        ),
    ]
