# Generated by Django 5.2 on 2025-05-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0014_alter_leads_lead_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'CompanyProfile', 'verbose_name_plural': 'CompanyProfiles'},
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
