# Generated by Django 5.2 on 2025-05-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0016_employee_email_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='employee_profiles/'),
        ),
    ]
