# Generated by Django 5.2 on 2025-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0018_remove_leads_products_interested_product_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='products_interested',
            field=models.ManyToManyField(blank=True, through='leads_app.LeadProduct', to='leads_app.product'),
        ),
    ]
