# Generated by Django 5.2 on 2025-05-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0020_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='q_coverpage',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pages/'),
        ),
    ]
